services:
  research-agent:
    build: .
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      PINECONE_API_KEY: "${PINECONE_API_KEY}"
      SERPAPI_API_KEY: "${SERPAPI_API_KEY}"
    volumes:
      - .:/app
